name: Solar System Workflow

on: 
  push:
    branches:
      - main
      - workflows

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:
    unit-testing:
        name: Unit Testing
        services:
          mongo:
            image: mongo
            ports:
              - 27017:27017
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        strategy:
          matrix:
            node-version: [18]
            os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        permissions:
          packages: write
          contents: read
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            # registry-url: 'https://npm.pkg.github.com'

        - name: Cache NPM Dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}
    
        - name: Install Dependencies
          run: npm install

        - name: Update Mongoose
          run: npm install mongoose@latest
    
        - name: Unit Testing
          id: test
          run: npm test
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result-${{ matrix.node-version }}-${{ matrix.os }}
            path: test-results.xml

        # - name: Publish to GitHub Repository
        #   run: npm publish
        #   env:
        #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    code-coverage:
        name: Code Coverage
        container:
          image: node:18
        services:
          mongo:
            image: mongo
            options:
              --name github
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}  
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        # - name: Setup NodeJS Version - 18
        #   uses: actions/setup-node@v3
        #   with:
        #     node-version: 18

        - name: Install Dependencies
          run: npm install

        - name: Update Mongoose
          run: npm install mongoose@latest

        - name: Code Coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive Code Coverage Result
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 7
    
    docker:
      name: Docker
      needs: [unit-testing, code-coverage]
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

      - name: Docker Image Test
        run: |
          docker images
          docker run --name solar-system -d \
            -p 3000:3000 \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
            -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system)
          echo $IP

          echo Testing image URL using wget
          wget -q -O - 127.0.0.1:3000/live | grep live

      - name: Container Registry Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: | 
            ghcr.io/b4rz99/solar-system:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

    dev-deploy:
      needs: docker
      runs-on: ubuntu-latest
      environment: Development
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.28.1

      - name: Set Kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
        

      - name: Fetch Kubernetes Cluster Details
        run: |
          kubectl version --client
          echo ---------------------------------------
          kubectl get nodes
          kubectl config current-context
          kubectl config get-contexts

      - name: Save Nginx Ingress Controller IP as a GitHub Variable
        run: |
          echo "INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Replace Token in Manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "_{_"
          tokenSuffix: "_}_"
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Check Kubernetes Files
        run: |
          cat kubernetes/development/*.yaml